### ISSUE TITLE
[Enhancement] add warmup for benchmark

### ISSUE THREAD

**Issue by alanzhai219** [zhangchaosd/ModelInferBench#1]
Hi,
I review the benchmark codes and everything looks good. But there is no warmup in the measurement.
For a standard benchmark flow, some warmups should be executed first.

**Comment by zhangchaosd** [comment]
Hi @alanzhai219 ,
Thank you so much for your insightful feedback and for taking the time to review this project.
I've indeed observed that the very first inference with the model can take a significantly longer time.
Regarding the warmup phase you mentioned, in our current implementation, we perform 20 inferences with the model and only use the results of the last 10 for averaging. The initial 10 inferences essentially serve as a warm-up phase. Would this process align with what you were referring to as the warmup stage?

We truly appreciate any suggestions or questions you might have, and we're open to further discussions.
Once again, thank you for your valuable input!
