### ISSUE TITLE
[Enhancement] configure the openvino for better performance

### ISSUE THREAD

**Issue by alanzhai219** [zhangchaosd/ModelInferBench#2]
Hi, if you invoke openvino inference, some mode settings can help improve the latency or throughput.
please refer to:
- https://docs.openvino.ai/nightly/notebooks/109-latency-tricks-with-output.html
- https://docs.openvino.ai/nightly/notebooks/109-throughput-tricks-with-output.html

**Comment by zhangchaosd** [comment]
Hi @alanzhai219 ,

Thank you for pointing this out and providing the reference. I truly appreciate your suggestion. I'll look into the OpenVINO mode settings you mentioned and explore potential improvements for the latency based on your input.

Your feedback is invaluable, and I'll strive to integrate it into the project to enhance its performance.I'll update this issue once the changes have been implemented.

Thanks again for your contribution!
